apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-green
  labels:
    app: html
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html
      version: green
  template:
    metadata:
      labels:
        app: html
        version: green
    spec:
      containers:
        - name: nginx
          image: sandy16docker/bluegreen:<IMAGE_TAG>
          imagePullPolicy: Always

          ports:
            - containerPort: 80
