apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: html
    version: <DEPLOY_COLOR> # replace with blue or green in pipeline
