apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html
    version: blue # initially blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
